begin;
select plan(17);
select has_table('campaign','funnel_publications','reviewed publications exist separately from private drafts');
select has_table('campaign','funnel_inquiries','consented requests have their own encrypted store');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='campaign.funnel_publications'::regclass),'publications force RLS');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='campaign.funnel_inquiries'::regclass),'inquiries force RLS');
select ok(has_table_privilege('app_runtime','campaign.funnel_publications','SELECT,INSERT'),'runtime can publish under tenant policy');
select ok(not has_column_privilege('app_runtime','campaign.funnel_publications','snapshot','UPDATE'),'published snapshots cannot be silently overwritten');
select ok(has_column_privilege('app_runtime','campaign.funnel_publications','active','UPDATE'),'owner can take a page offline');
select ok(not has_table_privilege('app_runtime','campaign.funnel_inquiries','INSERT'),'public receipt function is the only ordinary insertion path');
select ok(not has_table_privilege('app_runtime','campaign.funnel_inquiries','UPDATE'),'runtime cannot mark its own request delivered by direct SQL');
select ok(not has_table_privilege('support_runtime','campaign.funnel_inquiries','SELECT'),'support cannot read inquiries');
select ok(not has_table_privilege('reporting_runtime','campaign.funnel_inquiries','SELECT'),'reporting cannot read contact ciphertext');
select ok(not has_table_privilege('anon','campaign.funnel_inquiries','SELECT'),'anonymous clients cannot read inquiries');
select ok(not has_function_privilege('anon','campaign.funnel_public_snapshot(uuid)','EXECUTE'),'public data projection is invoked only by the server');
select ok(not has_function_privilege('authenticated','campaign.funnel_accept_inquiry(uuid,uuid,text,text,text,text,text)','EXECUTE'),'Supabase browser roles cannot bypass the form boundary');
select ok(has_function_privilege('app_runtime','campaign.funnel_accept_inquiry(uuid,uuid,text,text,text,text,text)','EXECUTE'),'server can accept bounded requests');
select ok((select bool_and(prosecdef and proconfig @> array['search_path=""']) from pg_proc where pronamespace='campaign'::regnamespace and proname in ('funnel_public_snapshot','funnel_accept_inquiry','funnel_receipt_valid','funnel_claim_delivery','funnel_finish_delivery')),'capability functions have fixed empty search paths');
select ok(not exists(select 1 from information_schema.columns where table_schema='campaign' and table_name='funnel_inquiries' and column_name in ('email','phone','first_name','ip_address')),'contact and address fields are not plaintext columns');
select * from finish();
rollback;
