import denylistEntries from "./password-denylist.json" with { type: "json" };
import { MAXIMUM_PASSWORD_LENGTH, normalizePassword } from "./password-hash.js";

/**
 * PRD-006a D3. The one password policy, applied at sign-up, at reset, at change, and in the
 * seeding script, so a password that is acceptable in one place is acceptable in all of them.
 *
 * **The denylist and where it comes from.** `password-denylist.json` holds 42,831 lowercase
 * entries, 19,001 of them twelve characters or longer, which is the range this policy's length
 * floor actually reaches. It is generated by
 * `tooling/scripts/auth/build-password-denylist.mjs` from a seed set of the best-known weak
 * passwords crossed with the suffix, year, name, and word-pair patterns that make a long password
 * guessable anyway; running that script reproduces the file byte for byte.
 *
 * It is first-party data authored in this repository and carries this repository's licence, so
 * there is no third-party licence to honour and no supply-chain entry to audit. D3 asked for "a
 * permissively licensed list of at least 10,000 entries"; the agent that built this had no network
 * access and could not vendor a published corpus, so it generated one instead and recorded the
 * choice here rather than pretending to a provenance it does not have. Swapping in SecLists'
 * `10-million-password-list-top-10000.txt` (MIT) is a drop-in replacement whenever someone with
 * network access wants it: the loader only needs an array of lowercase strings.
 *
 * The list is data, not a dependency: nothing is installed, and the JSON import is resolved at
 * build time.
 */

export const MINIMUM_PASSWORD_LENGTH = 12;

export const PASSWORD_POLICY_REASONS = Object.freeze([
  "PASSWORD_TOO_SHORT",
  "PASSWORD_TOO_LONG",
  "PASSWORD_LOOKS_PERSONAL",
  "PASSWORD_TOO_COMMON",
] as const);

export type PasswordPolicyReason = (typeof PASSWORD_POLICY_REASONS)[number];

export interface PasswordPolicyResult {
  readonly acceptable: boolean;
  readonly reason?: PasswordPolicyReason;
}

export interface PasswordPolicyContext {
  /** The address the person is signing up or signing in with, if one is known yet. */
  readonly email?: string;
  /** The name the person gave, if one is known yet. */
  readonly displayName?: string;
}

const denylist: ReadonlySet<string> = new Set(denylistEntries as readonly string[]);

/** Exposed so a test can assert the list is large enough without re-reading the JSON. */
export const PASSWORD_DENYLIST_SIZE = denylist.size;

const ACCEPTED: PasswordPolicyResult = Object.freeze({ acceptable: true });

function refuse(reason: PasswordPolicyReason): PasswordPolicyResult {
  return Object.freeze({ acceptable: false, reason });
}

/**
 * The personal fragments a password must not contain. The email's local part is the whole part
 * before the at sign; the display name contributes both the whole name and each of its
 * whitespace-separated parts, because "Jane" inside a long passphrase is exactly as guessable for
 * someone called Jane Miller as "Jane Miller" is.
 *
 * Fragments shorter than four characters are dropped: refusing every password containing "Jo"
 * would refuse most passwords and teach nobody anything.
 */
function personalFragments(context: PasswordPolicyContext): readonly string[] {
  const fragments: string[] = [];
  const localPart = context.email?.split("@")[0]?.trim().toLowerCase() ?? "";
  if (localPart.length >= 4) fragments.push(localPart);
  const displayName = context.displayName?.trim().toLowerCase() ?? "";
  if (displayName.length >= 4) fragments.push(displayName);
  for (const part of displayName.split(/\s+/u)) {
    if (part.length >= 4) fragments.push(part);
  }
  return fragments;
}

/**
 * D3. No composition rules: no required digit, symbol, or case. Length plus a denylist plus the
 * personal-fragment rule is what actually resists guessing, and a symbol requirement mostly
 * produces `Password1!`.
 *
 * The password is never trimmed and never logged. The result names a reason code; PRD-006b D10
 * owns the sentence each code renders as.
 */
export function evaluatePassword(
  password: string,
  context: PasswordPolicyContext = {},
): PasswordPolicyResult {
  const normalized = normalizePassword(password);
  if (normalized.length < MINIMUM_PASSWORD_LENGTH) return refuse("PASSWORD_TOO_SHORT");
  if (normalized.length > MAXIMUM_PASSWORD_LENGTH) return refuse("PASSWORD_TOO_LONG");

  const folded = normalized.toLowerCase();
  for (const fragment of personalFragments(context)) {
    if (folded.includes(fragment)) return refuse("PASSWORD_LOOKS_PERSONAL");
  }
  if (denylist.has(folded)) return refuse("PASSWORD_TOO_COMMON");
  return ACCEPTED;
}

export function isPasswordPolicyReason(value: unknown): value is PasswordPolicyReason {
  return (
    typeof value === "string" && (PASSWORD_POLICY_REASONS as readonly string[]).includes(value)
  );
}
