import { z } from "zod";

export * from "./tenant-installation.js";

export const contractVersion = "2026-07-20" as const;

export const FixtureValidationRequestSchema = z
  .object({
    schemaVersion: z.literal(1),
    fixtureSet: z.literal("rendering-v1"),
  })
  .strict();

export type FixtureValidationRequest = z.infer<typeof FixtureValidationRequestSchema>;

export {
  AuthoritySnapshotSchema,
  CommandEnvelopeSchema,
  CommandNameSchema,
  DeliveryReferenceSchema,
  OutboxEventSchema,
  ProviderOperationSchema,
  TaskReferenceSchema,
  durableContractVersion,
  type AuthoritySnapshot,
  type CommandEnvelope,
  type DeliveryReference,
  type OutboxEvent,
  type ProviderOperation,
  type TaskReference,
} from "./durable-foundation.js";

export {
  ArtifactRecordSchema,
  ArtifactTypeSchema,
  PaidAdRenderAssetManifestInputSchema,
  PaidAdRenderAssetManifestSchema,
  PublishedCampaignProjectionSchema,
  RenderManifestSchema,
  StorageTransferRequestSchema,
  type ArtifactRecord,
  type ArtifactType,
  type PaidAdRenderAsset,
  type PaidAdRenderAssetManifest,
  type PaidAdRenderAssetManifestInput,
  type PublicationCleanupIntent,
  type PublicationCleanupLease,
  type PublishedCampaignProjection,
  type RenderManifest,
  type StorageTransferRequest,
} from "./rendering-storage.js";

export {
  BrandSuggestionFieldSchema,
  BrandSuggestionSchema,
  CompiledBrandRulesSchema,
  ProfileAssetSchema,
  ProfileAttestationSchema,
  ProfileFieldSchema,
  ProfileReadinessContextSchema,
  ProfileReadinessResultSchema,
  ProfileTypeSchema,
  ProfileValueSchema,
  ProfileVersionInputSchema,
  ProfileVersionSchema,
  ProviderMappingSchema,
  type BrandSuggestion,
  type BrandSuggestionField,
  type CompiledBrandRules,
  type ProfileAsset,
  type ProfileField,
  type ProfileReadinessContext,
  type ProfileReadinessResult,
  type ProfileType,
  type ProfileValue,
  type ProfileVersion,
  type ProfileVersionInput,
  type ProviderMapping,
} from "./profile-foundation.js";

export {
  ApprovalDecisionSchema,
  ApprovalLinkClaimsSchema,
  ApprovalSnapshotSchema,
  CampaignEventSchema,
  CampaignInputVersionsSchema,
  CampaignManifestSchema,
  CampaignStateSchema,
  CampaignVersionInputSchema,
  CampaignVersionSchema,
  CollateralProjectionInputSchema,
  CollateralProjectionSchema,
  GenerationRecordSchema,
  PaidAdBrandBoundaryRulesSchema,
  PaidAdBrandPreflightEvidenceSchema,
  PaidAdProjectionInputSchema,
  PaidAdProjectionSchema,
  ProjectionApprovalDecisionSchema,
  PreflightFindingSchema,
  PreflightResultSchema,
  PreflightRulesSchema,
  type ApprovalDecision,
  type ApprovalLinkClaims,
  type ApprovalSnapshot,
  type CampaignEvent,
  type CampaignInputVersions,
  type CampaignManifest,
  type CampaignState,
  type CampaignVersion,
  type CampaignVersionInput,
  type CollateralProjection,
  type CollateralProjectionInput,
  type GenerationRecord,
  type PaidAdBrandBoundaryRules,
  type PaidAdBrandPreflightEvidence,
  type PaidAdProjection,
  type PaidAdProjectionInput,
  type ProjectionApprovalDecision,
  type PreflightFinding,
  type PreflightResult,
  type PreflightRules,
} from "./campaign-foundation.js";

export {
  AcceptedGenerationSchema,
  AiAssistedBrandProfileReviewSchema,
  AiTraceRecordSchema,
  AiUsageEventSchema,
  BrandSampleSchema,
  BrandSuggestionSetSchema,
  CampaignGenerationRequestSchema,
  EvaluationCaseResultSchema,
  ExtractedBrandSuggestionFieldSchema,
  ExtractedBrandSuggestionSchema,
  FrozenGenerationInputsSchema,
  GoldenEvaluationCaseSchema,
  GoldenEvaluationCorpusSchema,
  GeneratedTextPackSchema,
  GeneratedTextPieceSchema,
  GenerationPreflightSchema,
  ModelEvaluationResultSchema,
  ModelPolicySchema,
  ModelRouteSchema,
  PromptPolicySchema,
  ProviderFailureClassificationSchema,
  ProviderTokenUsageSchema,
  TextPieceRequestSchema,
  type AcceptedGeneration,
  type AiAssistedBrandProfileReview,
  type AiTraceRecord,
  type AiUsageEvent,
  type BrandSample,
  type BrandSuggestionSet,
  type CampaignGenerationRequest,
  type EvaluationCaseResult,
  type ExtractedBrandSuggestion,
  type ExtractedBrandSuggestionField,
  type FrozenGenerationInputs,
  type GoldenEvaluationCase,
  type GoldenEvaluationCorpus,
  type GeneratedTextPack,
  type GeneratedTextPiece,
  type GenerationPreflight,
  type ModelEvaluationResult,
  type ModelPolicy,
  type ModelRoute,
  type PromptPolicy,
  type ProviderFailureClassification,
  type ProviderTokenUsage,
  type TextPieceRequest,
} from "./ai-generation.js";

export {
  AttributionEventSchema,
  AttributionMilestoneSchema,
  CampaignLeadAuthoritySchema,
  ConsentReceiptSchema,
  LeadRoutingCommandSchema,
  LeadRoutingMappingsSchema,
  LeadRoutingResultSchema,
  PrivateLeadPayloadSchema,
  PublicLeadSubmissionSchema,
  type AttributionEvent,
  type AttributionMilestone,
  type CampaignLeadAuthority,
  type ConsentReceipt,
  type LeadRoutingCommand,
  type LeadRoutingMappings,
  type LeadRoutingResult,
  type PrivateLeadPayload,
  type PublicLeadSubmission,
} from "./lead-routing.js";

export {
  ApplicationRoleSchema,
  LaunchReadinessResultSchema,
  OnboardingEventSchema,
  ReadinessBlockSchema,
  ReadinessDependencySchema,
  ReadinessEvidenceSchema,
  ReadinessStepStatusSchema,
  type ApplicationRole,
  type LaunchReadinessResult,
  type OnboardingEvent,
  type ReadinessBlock,
  type ReadinessDependency,
  type ReadinessEvidence,
  type ReadinessStepStatus,
} from "./launch-readiness.js";

export {
  BlueprintAggregateSchema,
  BlueprintDimensionsSchema,
  BlueprintObservationSchema,
  CampaignReportingRecordSchema,
  CohortEventNameSchema,
  CohortEventSchema,
  CollaboratorAuditEventSchema,
  LocationAuthorizationSchema,
  RealtorCampaignAssignmentSchema,
  RealtorCampaignProjectionSchema,
  ReportingExceptionSchema,
  ReportingMetricSchema,
  ReportingMetricSourceSchema,
  type BlueprintAggregate,
  type BlueprintDimensions,
  type BlueprintObservation,
  type CampaignReportingRecord,
  type CohortEvent,
  type CohortEventName,
  type CollaboratorAuditEvent,
  type LocationAuthorization,
  type RealtorCampaignAssignment,
  type RealtorCampaignProjection,
  type ReportingException,
  type ReportingMetric,
  type ReportingMetricSource,
} from "./reporting.js";

export {
  CANONICAL_REFERENCE_CODECS,
  CANONICAL_REFERENCE_KINDS,
  CanonicalReferenceError,
  CanonicalReferenceSchema,
  actorReference,
  formatActorRef,
  formatInstallationRef,
  formatLocationRef,
  formatSessionRef,
  installationReference,
  locationReference,
  parseActorRef,
  parseInstallationRef,
  parseLocationRef,
  parseSessionRef,
  sessionReference,
  type CanonicalReferenceCodec,
  type CanonicalReferenceKind,
} from "./canonical-reference.js";
