/** CSS variable references for the public semantic UI token contract. */
export const uiTokens = Object.freeze({
  surface: Object.freeze({
    canvas: "var(--sf-canvas)",
    card: "var(--sf-card)",
    sunken: "var(--sf-sunken)",
    navigation: "var(--sf-nav)",
    overlay: "var(--sf-overlay)",
  }),
  text: Object.freeze({
    strong: "var(--tx-strong)",
    body: "var(--tx-body)",
    faint: "var(--tx-faint)",
    onAction: "var(--tx-on-action)",
    onNavigation: "var(--tx-on-nav)",
  }),
  border: Object.freeze({
    hairline: "var(--bd-hairline)",
    input: "var(--bd-input)",
  }),
  action: Object.freeze({
    primary: "var(--ac-primary)",
    primaryHover: "var(--ac-primary-hover)",
    primaryActive: "var(--ac-primary-active)",
    secondary: "var(--ac-secondary)",
  }),
  status: Object.freeze({
    successForeground: "var(--st-success-fg)",
    successBackground: "var(--st-success-bg)",
    warningForeground: "var(--st-warning-fg)",
    warningBackground: "var(--st-warning-bg)",
    criticalForeground: "var(--st-critical-fg)",
    criticalBackground: "var(--st-critical-bg)",
    infoForeground: "var(--st-info-fg)",
    infoBackground: "var(--st-info-bg)",
    neutralForeground: "var(--st-neutral-fg)",
    neutralBackground: "var(--st-neutral-bg)",
    uncertainForeground: "var(--st-uncertain-fg)",
    uncertainBackground: "var(--st-uncertain-bg)",
  }),
  focus: Object.freeze({
    color: "var(--focus-color)",
    width: "var(--focus-width)",
    offset: "var(--focus-offset)",
  }),
  elevation: Object.freeze({
    rest: "var(--shadow-rest)",
    card: "var(--shadow-card)",
    raised: "var(--shadow-raised)",
  }),
  typography: Object.freeze({
    interfaceFamily: "var(--font-interface)",
    dataFamily: "var(--font-data)",
    pageSize: "var(--text-page-size)",
    sectionSize: "var(--text-section-size)",
    cardSize: "var(--text-card-size)",
    bodySize: "var(--text-body-size)",
    secondarySize: "var(--text-secondary-size)",
    captionSize: "var(--text-caption-size)",
    regularWeight: "var(--weight-regular)",
    mediumWeight: "var(--weight-medium)",
    boldWeight: "var(--weight-bold)",
    pageTracking: "var(--tracking-page)",
    tightLeading: "var(--leading-tight)",
    normalLeading: "var(--leading-normal)",
  }),
  spacing: Object.freeze({
    1: "var(--space-1)",
    2: "var(--space-2)",
    3: "var(--space-3)",
    4: "var(--space-4)",
    5: "var(--space-5)",
    6: "var(--space-6)",
    8: "var(--space-8)",
  }),
  radius: Object.freeze({
    control: "var(--radius-control)",
    button: "var(--radius-button)",
    card: "var(--radius-card)",
    panel: "var(--radius-panel)",
    pill: "var(--radius-pill)",
  }),
  breakpoint: Object.freeze({
    mobile: "var(--breakpoint-mobile)",
    tablet: "var(--breakpoint-tablet)",
    embedded: "var(--breakpoint-embedded)",
    desktop: "var(--breakpoint-desktop)",
  }),
  motion: Object.freeze({
    fast: "var(--motion-fast)",
    base: "var(--motion-base)",
    slow: "var(--motion-slow)",
    standardEasing: "var(--ease-standard)",
  }),
});

export type UiTokens = typeof uiTokens;
