import { contractVersion } from "@oalo/contracts";

export const aiPackage = Object.freeze({
  contractVersion,
  implementation: "production-generation-contract",
});

export {
  AiGenerationError,
  AiSpendLimitError,
  LocationAiSpendGuard,
  UnsafeAiInputError,
  compileCampaignPrompt,
  customerAllowanceView,
  evaluateModelPromotion,
  extractBrandSuggestions,
  generateCampaignTextPack,
  reconcileProviderCost,
  validateBrandSamples,
  type AiClockPort,
  type AiHashPort,
  type AiIdentityPort,
  type AiProviderPort,
  type AiRuntimePorts,
  type AiSpendGuardPort,
  type AiSpendReservation,
  type AiTracePort,
  type AiUsagePort,
  type BrandExtractionRequest,
  type CampaignGenerationOptions,
  type CampaignGenerationPorts,
  type CompiledAiPrompt,
  type GenerationAllowancePort,
  type GenerationCommitPort,
  type GenerationLedgerPort,
  type GenerationPreflightPort,
  type LocationAiGuardOptions,
  type ProviderAttempt,
  type ProviderAttemptFailure,
  type ProviderAttemptSuccess,
  type ProviderCallInput,
} from "./production-generation.js";
