import { contractVersion } from "@oalo/contracts";

export const aiPackage = Object.freeze({
  contractVersion,
  implementation: "production-generation-contract",
});

export {
  AnthropicProviderConfigurationError,
  AnthropicProviderResponseError,
  createAnthropicMessagesProviderClient,
  type AiAbortSignal,
  type AiFetchTransport,
  type AiHttpResponse,
  type AnthropicMessagesProviderClient,
  type AnthropicMessagesProviderConfig,
  type AnthropicMessagesProviderDependencies,
  type AnthropicModelPricing,
  type AnthropicProviderProbeResult,
} from "./anthropic-messages-provider.js";

export {
  AiGenerationError,
  AiGenerationInProgressError,
  AiSpendLimitError,
  AiTelemetryReconciliationError,
  LocationAiSpendGuard,
  UnsafeAiInputError,
  compileCampaignPrompt,
  createInjectedProviderPort,
  customerAllowanceView,
  evaluateModelPromotion,
  extractBrandSuggestions,
  generateCampaignTextPack,
  reconcileProviderCost,
  validateBrandSamples,
  type AiClockPort,
  type AiHashPort,
  type AiIdentityPort,
  type AiProviderPort,
  type AiRuntimePorts,
  type AiSpendGuardPort,
  type AiSpendReservation,
  type AiTracePort,
  type AiTelemetryPort,
  type AiUsagePort,
  type BrandExtractionRequest,
  type CampaignGenerationOptions,
  type CampaignGenerationPorts,
  type CompiledAiPrompt,
  type GenerationAllowancePort,
  type GenerationCommitPort,
  type GenerationLedgerPort,
  type GenerationPreflightPort,
  type InjectedAiProviderTransport,
  type LocationAiGuardOptions,
  type ProviderAttempt,
  type ProviderAttemptFailure,
  type ProviderAttemptSuccess,
  type ProviderCallInput,
} from "./production-generation.js";
